#!/usr/bin/python3 -u

import zebr0

import zebr0_script

argparser = zebr0.ArgumentParser(description="Minimalist local provisioning.")
argparser.add_argument("-d", "--directory", default="/var/zebr0/history", help="path to the history files directory (default: /var/zebr0/history)")

argparser.add_argument("command", choices=["history", "run"])
argparser.add_argument("script", nargs="?", default="script", help="script identifier in the repository (default: script)")
argparser.add_argument("--dry", action="store_true", help="tests the script instead of running it")
argparser.add_argument("--step", action="store_true", help="asks confirmation before running each step")

args = argparser.parse_args()
client = zebr0.Client(args.url, args.levels, args.cache, args.configuration_file)

# calls the method given as parameter
if args.command == "history":
    zebr0_script.history(args.directory)
else:
    zebr0_script.run(args.script, args.directory, args.dry, args.step, client)
