#!/usr/bin/python3 -u

import zebr0

import zebr0_script

argparser = zebr0.build_argument_parser(description="Minimalist local provisioning.")
argparser.add_argument("-d", "--directory", default="/var/zebr0/history", help="path to the history files directory (default: /var/zebr0/history)")
subparsers = argparser.add_subparsers()

history_parser = subparsers.add_parser("history")
history_parser.set_defaults(command=zebr0_script.history)

run_parser = subparsers.add_parser("run")
run_parser.add_argument("script", nargs="?", default="script", help="script identifier in the repository (default: script)")
run_parser.add_argument("--dry", action="store_true", help="tests the script instead of running it")
run_parser.add_argument("--step", action="store_true", help="asks confirmation before running each step")
run_parser.set_defaults(command=zebr0_script.run)

args = argparser.parse_args()
args.command(**vars(args))
